// Generated by Style Dictionary — do not edit.
import CoreGraphics

public enum Radius {
    public static let sm: CGFloat = 10
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 14
    public static let xl: CGFloat = 16
    public static let xxl: CGFloat = 18
    public static let pill: CGFloat = 22
}

public enum Space {
    public static let xxs: CGFloat = 4
    public static let xs: CGFloat = 8
    public static let sm: CGFloat = 12
    public static let md: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
}

public enum FontWeightToken {
    public static let regular: Int = 400
    public static let medium: Int = 500
    public static let semibold: Int = 600
    public static let bold: Int = 700
}

public enum FontTracking {
    public static let normal: CGFloat = 0
    public static let eyebrow: CGFloat = 1.3
    public static let wide: CGFloat = 2
}
