import StyleDictionary from 'style-dictionary';

const GEN_HEADER = 'Generated by Style Dictionary — do not edit.';

// CSS var name for a token: explicit override, else --group-leaf (kebab).
function cssVar(token) {
  const override = token.$extensions?.shroom?.css;
  if (override) return override;
  return '--' + token.path.join('-').toLowerCase();
}
function isSwiftOnly(t) { return t.$extensions?.shroom?.swiftOnly === true; }

function dimPx(token) {
  // dimension values are unitless numbers-as-strings → append px for CSS
  const v = String(token.$value ?? token.value);
  return /^[0-9.]+$/.test(v) ? `${v}px` : v;
}

StyleDictionary.registerFormat({
  name: 'shroom/css',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens.filter((t) => !isSwiftOnly(t));
    const isColor = (t) => t.$type === 'color' || t.type === 'color';
    const themeBlock = (theme) => all
      .filter((t) => isColor(t) && t.path[0] === 'color' && t.path[1] === theme)
      .map((t) => {
        const val = t.$value ?? t.value;
        return `  ${cssVar(t)}: ${val};`;
      }).join('\n');
    const scaleBlock = all
      .filter((t) => {
        const type = t.$type ?? t.type;
        return type === 'dimension' || type === 'fontWeight' || type === 'fontFamily';
      })
      .map((t) => {
        const type = t.$type ?? t.type;
        const val = t.$value ?? t.value;
        const cssVal = type === 'dimension' ? dimPx(t) : String(val);
        return `  ${cssVar(t)}: ${cssVal};`;
      }).join('\n');
    return [
      `/* ${GEN_HEADER} */`,
      `:root, [data-theme="forest"] {`,
      themeBlock('forest'),
      scaleBlock,
      `}`,
      ``,
      `[data-theme="twilight"] {`,
      themeBlock('twilight'),
      `}`,
      ``,
    ].join('\n');
  },
});

function swiftHex(token) {
  // resolved color value "#RRGGBB" → 0xRRGGBB
  return '0x' + String(token.$value).replace('#', '').toUpperCase();
}

// Swift-legal leaf names (no leading digit).
const SWIFT_SCALE_NAME = { '2xs': 'xxs', '2xl': 'xxl' };
function swiftLeaf(name) { return SWIFT_SCALE_NAME[name] ?? name; }

// MUST mirror the per-theme color tokens in tokens.json (color.forest.*,
// color.twilight.*), excluding `warn` (computed alias) and the cssOnly chrome
// tokens (frame/island/homeBar). This explicit order is what freezes the
// generated `Palette` init signature — adding a palette color means adding it
// here AND in tokens.json. A name here with no matching token throws at build.
const PALETTE_ORDER = [
  'appBg','boardBg','text','sub','pill','accent','accentText',
  'tileCovered','tileCoveredHi','tileCoveredEdge','tileRevealed','tileRevealedEdge',
  'mushroomCap','mushroomStem','mushroomSpot','explodeBg',
  'markerPost','markerSign','markerInk','emptyMark','tierBorder','tierBg','tierSelBg',
];

StyleDictionary.registerFormat({
  name: 'shroom/palette-swift',
  format: ({ dictionary }) => {
    const colorFor = (theme, name) =>
      dictionary.allTokens.find((t) => t.path[0] === 'color' && t.path[1] === theme && t.path[2] === name);
    const themeStatic = (theme) => {
      const lines = PALETTE_ORDER.map((n) => `        ${n}: Color(hex: ${swiftHex(colorFor(theme, n))})`);
      const nums = ['.clear'];
      for (let i = 1; i <= 8; i++) {
        const t = dictionary.allTokens.find((x) => x.path[1] === theme && x.path[2] === 'numberColors' && x.path[3] === String(i));
        nums.push(`Color(hex: ${swiftHex(t)})`);
      }
      lines.push('        numberColors: [\n            ' + nums.join(',\n            ') + '\n        ]');
      return `    public static let ${theme} = Palette(\n${lines.join(',\n')}\n    )`;
    };
    return [
      `// ${GEN_HEADER}`,
      `import SwiftUI`,
      ``,
      `public struct Palette: Sendable {`,
      PALETTE_ORDER.map((n) => `    public let ${n}: Color`).join('\n'),
      `    public let numberColors: [Color]`,
      ``,
      `    public init(`,
      [...PALETTE_ORDER.map((n) => `        ${n}: Color`), `        numberColors: [Color]`].join(',\n'),
      `    ) {`,
      [...PALETTE_ORDER.map((n) => `        self.${n} = ${n}`), `        self.numberColors = numberColors`].join('\n'),
      `    }`,
      `}`,
      ``,
      `extension Palette {`,
      themeStatic('forest'),
      ``,
      themeStatic('twilight'),
      ``,
      `    public static func palette(for appearance: Appearance) -> Palette {`,
      `        switch appearance {`,
      `        case .forest:   return .forest`,
      `        case .twilight: return .twilight`,
      `        }`,
      `    }`,
      ``,
      `    public static func palette(for scheme: ColorScheme) -> Palette {`,
      `        scheme == .dark ? .twilight : .forest`,
      `    }`,
      ``,
      `    /// Semantic alias: over-fill / warning tone, shared with the mushroom cap.`,
      `    public var warn: Color { mushroomCap }`,
      `}`,
      ``,
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'shroom/scales-swift',
  format: ({ dictionary }) => {
    const dims = (group) => dictionary.allTokens
      .filter((t) => t.path[0] === group && t.$type === 'dimension')
      .map((t) => `    public static let ${swiftLeaf(t.path[1])}: CGFloat = ${t.$value}`).join('\n');
    const weights = dictionary.allTokens
      .filter((t) => t.path[0] === 'font' && t.path[1] === 'weight')
      .map((t) => `    public static let ${t.path[2]}: Int = ${t.$value}`).join('\n');
    const tracking = dictionary.allTokens
      .filter((t) => t.path[0] === 'font' && t.path[1] === 'tracking')
      .map((t) => `    public static let ${t.path[2]}: CGFloat = ${t.$value}`).join('\n');
    return [
      `// ${GEN_HEADER}`,
      `import CoreGraphics`,
      ``,
      `public enum Radius {`, dims('radius'), `}`,
      ``,
      `public enum Space {`, dims('space'), `}`,
      ``,
      `public enum FontWeightToken {`, weights, `}`,
      ``,
      `public enum FontTracking {`, tracking, `}`,
      ``,
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  // Two themes share leaf names (appBg, etc.) → SD warns about output-name
  // collisions. This is intentional; our custom format handles both themes
  // by filtering on path[1], so collisions in SD's internal name table are harmless.
  log: { warnings: 'disabled' },
  source: ['tokens/tokens.json'],
  platforms: {
    css: {
      transforms: [],
      buildPath: 'tokens/build/',
      files: [{ destination: 'tokens.css', format: 'shroom/css' }],
      options: { outputReferences: false },
    },
    swift: {
      transforms: [],
      buildPath: 'Sources/ShroomKit/Theme/',
      files: [
        { destination: 'Palette.swift', format: 'shroom/palette-swift' },
        { destination: 'Tokens.generated.swift', format: 'shroom/scales-swift' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
