import StyleDictionary from 'style-dictionary';

const GEN_HEADER = 'Generated by Style Dictionary — do not edit.';

// CSS var name for a token: explicit override, else --group-leaf (kebab).
function cssVar(token) {
  const override = token.$extensions?.shroom?.css;
  if (override) return override;
  return '--' + token.path.join('-').toLowerCase();
}
function isSwiftOnly(t) { return t.$extensions?.shroom?.swiftOnly === true; }

function dimPx(token) {
  // dimension values are unitless numbers-as-strings → append px for CSS
  const v = String(token.$value ?? token.value);
  return /^[0-9.]+$/.test(v) ? `${v}px` : v;
}

StyleDictionary.registerFormat({
  name: 'shroom/css',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens.filter((t) => !isSwiftOnly(t));
    const isColor = (t) => t.$type === 'color' || t.type === 'color';
    const themeBlock = (theme) => all
      .filter((t) => isColor(t) && t.path[0] === 'color' && t.path[1] === theme)
      .map((t) => {
        const val = t.$value ?? t.value;
        return `  ${cssVar(t)}: ${val};`;
      }).join('\n');
    const scaleBlock = all
      .filter((t) => {
        const type = t.$type ?? t.type;
        return type === 'dimension' || type === 'fontWeight' || type === 'fontFamily';
      })
      .map((t) => {
        const type = t.$type ?? t.type;
        const val = t.$value ?? t.value;
        const cssVal = type === 'dimension' ? dimPx(t) : String(val);
        return `  ${cssVar(t)}: ${cssVal};`;
      }).join('\n');
    return [
      `/* ${GEN_HEADER} */`,
      `:root, [data-theme="forest"] {`,
      themeBlock('forest'),
      scaleBlock,
      `}`,
      ``,
      `[data-theme="twilight"] {`,
      themeBlock('twilight'),
      `}`,
      ``,
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  // Two themes share leaf names (appBg, etc.) → SD warns about output-name
  // collisions. This is intentional; our custom format handles both themes
  // by filtering on path[1], so collisions in SD's internal name table are harmless.
  log: { warnings: 'disabled' },
  source: ['tokens/tokens.json'],
  platforms: {
    css: {
      transforms: [],
      buildPath: 'tokens/build/',
      files: [{ destination: 'tokens.css', format: 'shroom/css' }],
      options: { outputReferences: false },
    },
  },
});

await sd.buildAllPlatforms();
